/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ambiata.notion.distcopy;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MappingsLookup implements org.apache.thrift.TBase<MappingsLookup, MappingsLookup._Fields>, java.io.Serializable, Cloneable, Comparable<MappingsLookup> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MappingsLookup");

  private static final org.apache.thrift.protocol.TField MAPPINGS_FIELD_DESC = new org.apache.thrift.protocol.TField("mappings", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MappingsLookupStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MappingsLookupTupleSchemeFactory());
  }

  public List<MappingLookup> mappings; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MAPPINGS((short)1, "mappings");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MAPPINGS
          return MAPPINGS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MAPPINGS, new org.apache.thrift.meta_data.FieldMetaData("mappings", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MappingLookup.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MappingsLookup.class, metaDataMap);
  }

  public MappingsLookup() {
  }

  public MappingsLookup(
    List<MappingLookup> mappings)
  {
    this();
    this.mappings = mappings;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MappingsLookup(MappingsLookup other) {
    if (other.isSetMappings()) {
      List<MappingLookup> __this__mappings = new ArrayList<MappingLookup>(other.mappings.size());
      for (MappingLookup other_element : other.mappings) {
        __this__mappings.add(new MappingLookup(other_element));
      }
      this.mappings = __this__mappings;
    }
  }

  public MappingsLookup deepCopy() {
    return new MappingsLookup(this);
  }

  @Override
  public void clear() {
    this.mappings = null;
  }

  public int getMappingsSize() {
    return (this.mappings == null) ? 0 : this.mappings.size();
  }

  public java.util.Iterator<MappingLookup> getMappingsIterator() {
    return (this.mappings == null) ? null : this.mappings.iterator();
  }

  public void addToMappings(MappingLookup elem) {
    if (this.mappings == null) {
      this.mappings = new ArrayList<MappingLookup>();
    }
    this.mappings.add(elem);
  }

  public List<MappingLookup> getMappings() {
    return this.mappings;
  }

  public MappingsLookup setMappings(List<MappingLookup> mappings) {
    this.mappings = mappings;
    return this;
  }

  public void unsetMappings() {
    this.mappings = null;
  }

  /** Returns true if field mappings is set (has been assigned a value) and false otherwise */
  public boolean isSetMappings() {
    return this.mappings != null;
  }

  public void setMappingsIsSet(boolean value) {
    if (!value) {
      this.mappings = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MAPPINGS:
      if (value == null) {
        unsetMappings();
      } else {
        setMappings((List<MappingLookup>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MAPPINGS:
      return getMappings();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MAPPINGS:
      return isSetMappings();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MappingsLookup)
      return this.equals((MappingsLookup)that);
    return false;
  }

  public boolean equals(MappingsLookup that) {
    if (that == null)
      return false;

    boolean this_present_mappings = true && this.isSetMappings();
    boolean that_present_mappings = true && that.isSetMappings();
    if (this_present_mappings || that_present_mappings) {
      if (!(this_present_mappings && that_present_mappings))
        return false;
      if (!this.mappings.equals(that.mappings))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(MappingsLookup other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMappings()).compareTo(other.isSetMappings());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMappings()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mappings, other.mappings);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MappingsLookup(");
    boolean first = true;

    sb.append("mappings:");
    if (this.mappings == null) {
      sb.append("null");
    } else {
      sb.append(this.mappings);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MappingsLookupStandardSchemeFactory implements SchemeFactory {
    public MappingsLookupStandardScheme getScheme() {
      return new MappingsLookupStandardScheme();
    }
  }

  private static class MappingsLookupStandardScheme extends StandardScheme<MappingsLookup> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MappingsLookup struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MAPPINGS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.mappings = new ArrayList<MappingLookup>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  MappingLookup _elem2;
                  _elem2 = new MappingLookup();
                  _elem2.read(iprot);
                  struct.mappings.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setMappingsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MappingsLookup struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.mappings != null) {
        oprot.writeFieldBegin(MAPPINGS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.mappings.size()));
          for (MappingLookup _iter3 : struct.mappings)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MappingsLookupTupleSchemeFactory implements SchemeFactory {
    public MappingsLookupTupleScheme getScheme() {
      return new MappingsLookupTupleScheme();
    }
  }

  private static class MappingsLookupTupleScheme extends TupleScheme<MappingsLookup> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MappingsLookup struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMappings()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMappings()) {
        {
          oprot.writeI32(struct.mappings.size());
          for (MappingLookup _iter4 : struct.mappings)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MappingsLookup struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.mappings = new ArrayList<MappingLookup>(_list5.size);
          for (int _i6 = 0; _i6 < _list5.size; ++_i6)
          {
            MappingLookup _elem7;
            _elem7 = new MappingLookup();
            _elem7.read(iprot);
            struct.mappings.add(_elem7);
          }
        }
        struct.setMappingsIsSet(true);
      }
    }
  }

}

