/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ambiata.notion.distcopy;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MappingLookup extends org.apache.thrift.TUnion<MappingLookup, MappingLookup._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MappingLookup");
  private static final org.apache.thrift.protocol.TField UPLOAD_FIELD_DESC = new org.apache.thrift.protocol.TField("upload", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField DOWNLOAD_FIELD_DESC = new org.apache.thrift.protocol.TField("download", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    UPLOAD((short)1, "upload"),
    DOWNLOAD((short)2, "download");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // UPLOAD
          return UPLOAD;
        case 2: // DOWNLOAD
          return DOWNLOAD;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.UPLOAD, new org.apache.thrift.meta_data.FieldMetaData("upload", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, UploadMappingLookup.class)));
    tmpMap.put(_Fields.DOWNLOAD, new org.apache.thrift.meta_data.FieldMetaData("download", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, DownloadMappingLookup.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MappingLookup.class, metaDataMap);
  }

  public MappingLookup() {
    super();
  }

  public MappingLookup(_Fields setField, Object value) {
    super(setField, value);
  }

  public MappingLookup(MappingLookup other) {
    super(other);
  }
  public MappingLookup deepCopy() {
    return new MappingLookup(this);
  }

  public static MappingLookup upload(UploadMappingLookup value) {
    MappingLookup x = new MappingLookup();
    x.setUpload(value);
    return x;
  }

  public static MappingLookup download(DownloadMappingLookup value) {
    MappingLookup x = new MappingLookup();
    x.setDownload(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case UPLOAD:
        if (value instanceof UploadMappingLookup) {
          break;
        }
        throw new ClassCastException("Was expecting value of type UploadMappingLookup for field 'upload', but got " + value.getClass().getSimpleName());
      case DOWNLOAD:
        if (value instanceof DownloadMappingLookup) {
          break;
        }
        throw new ClassCastException("Was expecting value of type DownloadMappingLookup for field 'download', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case UPLOAD:
          if (field.type == UPLOAD_FIELD_DESC.type) {
            UploadMappingLookup upload;
            upload = new UploadMappingLookup();
            upload.read(iprot);
            return upload;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case DOWNLOAD:
          if (field.type == DOWNLOAD_FIELD_DESC.type) {
            DownloadMappingLookup download;
            download = new DownloadMappingLookup();
            download.read(iprot);
            return download;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case UPLOAD:
        UploadMappingLookup upload = (UploadMappingLookup)value_;
        upload.write(oprot);
        return;
      case DOWNLOAD:
        DownloadMappingLookup download = (DownloadMappingLookup)value_;
        download.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case UPLOAD:
          UploadMappingLookup upload;
          upload = new UploadMappingLookup();
          upload.read(iprot);
          return upload;
        case DOWNLOAD:
          DownloadMappingLookup download;
          download = new DownloadMappingLookup();
          download.read(iprot);
          return download;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case UPLOAD:
        UploadMappingLookup upload = (UploadMappingLookup)value_;
        upload.write(oprot);
        return;
      case DOWNLOAD:
        DownloadMappingLookup download = (DownloadMappingLookup)value_;
        download.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case UPLOAD:
        return UPLOAD_FIELD_DESC;
      case DOWNLOAD:
        return DOWNLOAD_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public UploadMappingLookup getUpload() {
    if (getSetField() == _Fields.UPLOAD) {
      return (UploadMappingLookup)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'upload' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setUpload(UploadMappingLookup value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.UPLOAD;
    value_ = value;
  }

  public DownloadMappingLookup getDownload() {
    if (getSetField() == _Fields.DOWNLOAD) {
      return (DownloadMappingLookup)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'download' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setDownload(DownloadMappingLookup value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.DOWNLOAD;
    value_ = value;
  }

  public boolean isSetUpload() {
    return setField_ == _Fields.UPLOAD;
  }


  public boolean isSetDownload() {
    return setField_ == _Fields.DOWNLOAD;
  }


  public boolean equals(Object other) {
    if (other instanceof MappingLookup) {
      return equals((MappingLookup)other);
    } else {
      return false;
    }
  }

  public boolean equals(MappingLookup other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(MappingLookup other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  /**
   * If you'd like this to perform more respectably, use the hashcode generator option.
   */
  @Override
  public int hashCode() {
    return 0;
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
